### ISSUE TITLE
Feature request: Write processes to file

### ISSUE THREAD

**Issue by kmille** [DominicBreuker/pspy#14]
- the `-p` is unnecessary because it's enabled  per default?
Would be nice if I can specify where to save the process log. A separate log for the filesystem monitoring would be nice too.

**Comment by DominicBreuker** [comment]
Better late than never: 
- the `-p` flag is on by default but not completely useless, since you can do `-p=false` to turn it off.
- As for saving output to a file, maybe redirection with `>` would be enough? I like to do something like `./pspy > /tmp/mylog` in one shell, then `tail -f /tmp/mylog` in another. You get the same live output but you can also `grep` better to home in on something.
